export const SETTING_KEYS = {
  PUBLIC_STRIPE: "stpkys",
  PRIVATE_STRIPE: "jwewjr",
  ACCESS_BUNNY: "bnnyky",
  HOST_BUNNY: "lnkhbn",
  CAPCHA_GOOGLE: "ECPTCHP",
  OAUTH_GITHUB: "LOGVGTS",
  OAUTH_GOOGLE: "LOGVAGG",
  OAUTH_FACEBOOK: "LOGVAFB",
  SIGN_IN_LIMIT: "LGONLIG",
};
